create table labReportInformation(
  id  int(10) NOT NULL auto_increment primary key,
  location_id  varchar(255),
  print_date varchar(10),
  print_time varchar(10),
  total_BType varchar(5),
  total_CType varchar(5),
  total_DType  varchar(5)
);



CREATE TABLE billing_on_diskname (
  id int(11) NOT NULL auto_increment,
  monthCode char(1) default '',
  batchcount int(3),
  ohipfilename varchar(50),
  groupno varchar(6) default NULL,
  creator char(6) default NULL,
  claimrecord varchar(10) default null,
  createdatetime datetime,
  status char(1) default NULL,
  total varchar(20) default null,
  timestamp timestamp,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_filename (
  id int(11) NOT NULL auto_increment,
  disk_id int(11) NOT NULL,
  htmlfilename varchar(50),
  providerohipno varchar(6) default NULL,
  providerno char(6) NOT NULL,
  claimrecord varchar(10) default null,
  status char(1) default NULL,
  total varchar(20) default null,
  timestamp timestamp,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_repo (
  id int(11) NOT NULL auto_increment,
  h_id int(11) NOT NULL,
  category varchar(60),
  content text,
  createdatetime datetime,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_proc (
  id int(11) NOT NULL auto_increment,
  creator varchar(6),
  action varchar(60)  default '',
  comment varchar(200)  default '',
  object varchar(60) default '',
  createdatetime datetime,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_header (
  id int(11) NOT NULL auto_increment,
  disk_id int(11) NOT NULL,
  transc_id char(2) default 'HE',
  rec_id char(1) default 'B',
  spec_id char(3) default 'V03',
  moh_office char(1) default '',
  batch_id varchar(12) default '',
  operator varchar(6) default '',
  group_num char(4) default '0000',
  provider_reg_num varchar(6) default '',
  specialty char(2) default '00',
  h_count varchar(4) default '0000',
  r_count varchar(4) default '0000',
  t_count varchar(5) default '00000',
  batch_date date,

  createdatetime datetime,
  updatedatetime datetime,
  creator varchar(6) default '',
  action varchar(60)  default '',
  comment varchar(200)  default '',
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_cheader1 (
  id int(12) NOT NULL auto_increment,
  header_id int(11) NOT NULL,
  transc_id char(2) default 'HE',
  rec_id char(1) default 'H',
  hin char(10) default NULL,
  ver char(2) default '  ',
  dob char(8) default NULL,
  ##acc_num char(8) default NULL,
  pay_program char(3) default 'HCP',
  payee char(1) default 'P',
  ref_num varchar(6) default NULL,
  facilty_num varchar(4) default NULL,
  admission_date varchar(10) default NULL,
  ref_lab_num varchar(4) default NULL,
  man_review char(1) default NULL,
  location varchar(4) default NULL,

  demographic_no int(10) NOT NULL default '0',
  provider_no varchar(6) NOT NULL default '',
  appointment_no int(12) default NULL,
  demographic_name varchar(60),
  sex char(1) default '1',
  province char(2) default 'ON',
  billing_date date default NULL,
  billing_time time default NULL,
  total decimal(10,2),
  paid decimal(10,2),
  status char(1) default NULL,
  comment1 text,
  visittype char(2) default NULL,
  provider_ohip_no varchar(20) default NULL,
  provider_rma_no varchar(20) default NULL,
  apptProvider_no varchar(6) default NULL,
  asstProvider_no varchar(6) default NULL,
  creator varchar(6) default NULL,
  timestamp1 timestamp,
  clinic varchar(30) default NULL,

  PRIMARY KEY  (id),
  KEY appointment_no (appointment_no,demographic_no),
  KEY demographic_no (demographic_no),
  KEY billing_date (billing_date),
  KEY provider_no (provider_no),
  KEY provider_ohip_no (provider_ohip_no),
  KEY apptProvider_no (apptProvider_no),
  KEY creator (creator),
  KEY clinic (clinic),
  KEY status (status)
) ;

CREATE TABLE billing_on_cheader2 (
  id int(12) NOT NULL auto_increment,
  ch1_id int(12) NOT NULL ,
  transc_id char(2) default 'HE',
  rec_id char(1) default 'R',
  hin char(12) default NULL,
  last_name char(9) default '  ',
  first_name char(5) default NULL,
  sex char(1) default '1',
  province char(2) default 'AB',
  timestamp timestamp,
  PRIMARY KEY  (id),
  KEY ch1_id (ch1_id)
) ;

CREATE TABLE billing_on_item (
  id int(12) NOT NULL auto_increment,
  ch1_id int(12) NOT NULL ,
  transc_id char(2) default 'HE',
  rec_id char(1) default 'T',
  service_code char(20) default NULL,
  fee varchar(7) default '',
  ser_num char(5),
  service_date date,
  dx char(4) default '',
  dx1 char(4) default '',
  dx2 char(4) default '',

  status char(1) default NULL,
  timestamp timestamp,
  PRIMARY KEY  (id),
  KEY ch1_id (ch1_id)
) ;

CREATE TABLE billing_on_favourite (
  id int(12) NOT NULL auto_increment,
  name varchar(60) default '',
  service_dx varchar(255) default '',
  provider_no varchar(6) default null,
  timestamp timestamp,
  deleted boolean NOT NULL default false,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_errorCode (
  code varchar(5) NOT NULL,
  description varchar(255) NOT NULL default '',
  PRIMARY KEY  (code)
) ;


CREATE TABLE billing_on_eareport (
  id int(12) NOT NULL auto_increment,
  providerohip_no varchar(6),
  group_no varchar(6) default '0000',
  specialty char(2) default '00',
  process_date date,
  hin varchar(12),
  ver char(2),
  dob date,
  billing_no int(6),
  ref_no varchar(6),
  facility varchar(4),
  admitted_date date,
  claim_error varchar(20),
  code varchar(5),
  fee varchar(10), 
  unit varchar(2),
  code_date date,
  dx varchar(5),
  exp varchar(60),
  code_error varchar(20),
  report_name varchar(20)  default '',
  status char(1) default 'N',
  comment varchar(100),

  PRIMARY KEY  (id),
  key (providerohip_no),
  key (code_date),
  key (process_date)
) ;

CREATE TABLE billing_on_ext (
  id int(12) NOT NULL auto_increment,
  billing_no int(6),
  demographic_no int(10) NOT NULL default '0',
  key_val varchar(50),
  value varchar(255) ,
  date_time datetime,
  status char(1) default '1',
  PRIMARY KEY  (id),
  key (key_val),
  key (billing_no),
  payment_id int(10)
) ;

CREATE TABLE ctl_billingtype (
    servicetype varchar(10) not null,
    billtype    varchar(5)  not null,
    primary key (servicetype)
);

CREATE TABLE `formLabReq07` (
  	`ID` int(10) NOT NULL auto_increment,
	`formEdited` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
	`b_glucose` tinyint(1) default NULL,
	`b_glucose_random` tinyint(1) default NULL,
	`b_glucose_fasting` tinyint(1) default NULL,
	`b_hba1c` tinyint(1) default NULL,
	`b_creatinine` tinyint(1) default NULL,
	`b_uricAcid` tinyint(1) default NULL,
	`b_sodium` tinyint(1) default NULL,
	`b_potassium` tinyint(1) default NULL,
	`b_chloride` tinyint(1) default NULL,
	`b_ck` tinyint(1) default NULL,
	`b_alt` tinyint(1) default NULL,
	`b_alkPhosphatase` tinyint(1) default NULL,
	`ohip` tinyint(1) default NULL,
	`formCreated` date default NULL,
	`patientFirstName` varchar(40) default NULL,
	`b_timeNextDose2` varchar(20) default NULL,
	`clinicCity` varchar(40) default NULL,
	`b_timeNextDose1` varchar(20) default NULL,
	`b_timeLastDose2` varchar(20) default NULL,
	`b_timeLastDose1` varchar(20) default NULL,
	`provider_no` int(11) default NULL,
	`m_vaginalRectal` tinyint(1) default NULL,
	`m_vaginal` tinyint(1) default NULL,
	`b_acRatioUrine` tinyint(1) default NULL,
	`healthNumber` varchar(20) default NULL,
	`patientCity` varchar(40) default NULL,
	`b_patientsTelNo` varchar(40) default NULL,
        `clinicianContactUrgent` varchar(40) default NULL,
	`b_childsAgeDays` varchar(20) default NULL,
	`b_tsh` tinyint(1) default NULL,
	`b_timeCollected2` varchar(20) default NULL,
	`b_timeCollected1` varchar(20) default NULL,
	`b_therapeuticDrugMonitoring` tinyint(1) default NULL,
	`i_rubella` tinyint(1) default NULL,
	`m_cervical` tinyint(1) default NULL,
	`patientAddress` varchar(60) default NULL,
	`b_vitaminB12` tinyint(1) default NULL,
	`m_blank` tinyint(1) default NULL,
	`reqProvName` varchar(60) default NULL,
	`v_chronicHepatitis` tinyint(1) default NULL,
	`version` varchar(6) default NULL,
	`oprn` varchar(40) default NULL,
	`b_albumin` tinyint(1) default NULL,
	`aci` text,
	`patientPC` varchar(10) default NULL,
	`b_urinalysis` tinyint(1) default NULL,
	`h_cbc` tinyint(1) default NULL,
	`form_class` tinyint(1) default NULL,
	`sex` varchar(8) default NULL,
	`i_pregnancyTest` tinyint(1) default NULL,
	`submit` tinyint(1) default NULL,
	`v_acuteHepatitis` tinyint(1) default NULL,
	`birthDate` date default NULL,
	`patientBirthMth` varchar(25) default NULL,
	`phoneNumber` varchar(20) default NULL,
	`m_otherSwabsSource` varchar(60) default NULL,
	`m_otherSwabsPus` tinyint(1) default NULL,
	`clinicAddress` varchar(100) default NULL,
	`m_gcSource` varchar(60) default NULL,
	`b_childsAgeHours` varchar(20) default NULL,
	`m_throat` tinyint(1) default NULL,
	`patientLastName` varchar(40) default NULL,
	`m_sputum` tinyint(1) default NULL,
	`b_neonatalBilirubin` tinyint(1) default NULL,
	`m_fecalOccultBlood` tinyint(1) default NULL,
	`m_urine` tinyint(1) default NULL,
        `m_blankText` varchar(100) default NULL,
	`b_nameDrug2` varchar(100) default NULL,
	`m_stoolOvaParasites` tinyint(1) default NULL,
	`b_nameDrug1` varchar(100) default NULL,
	`m_gc` tinyint(1) default NULL,
	`i_prenatal` tinyint(1) default NULL,
	`h_prothrombinTime` tinyint(1) default NULL,
	`patientBirthYear` varchar(10) default NULL,
	`m_chlamydiaSource` varchar(60) default NULL,
	`i_repeatPrenatalAntibodies` tinyint(1) default NULL,
	`b_ferritin` tinyint(1) default NULL,
	`wcb` tinyint(1) default NULL,
	`v_immuneStatus` tinyint(1) default NULL,
	`m_stoolCulture` tinyint(1) default NULL,
	`province` varchar(20) default NULL,
	`m_woundSource` varchar(60) default NULL,
	`patientBirthDay` varchar(30) default NULL,
	`demographic_no` int(11) default NULL,
	`i_mononucleosisScreen` tinyint(1) default NULL,
	`b_lipidAssessment` tinyint(1) default NULL,
	`m_wound` tinyint(1) default NULL,
	`provName` varchar(60) default NULL,
	`thirdParty` tinyint(1) default NULL,
	`clinicName` varchar(60) default NULL,
	`b_bilirubin` tinyint(1) default NULL,
        `m_specimenCollectionTime` varchar(15) default NULL,
	`o_otherTests16` varchar(150) default NULL,
	`o_otherTests15` varchar(150) default NULL,
	`o_otherTests14` varchar(150) default NULL,
	`o_otherTests13` varchar(150) default NULL,
	`o_otherTests12` varchar(150) default NULL,
	`o_otherTests11` varchar(150) default NULL,
	`o_otherTests10` varchar(150) default NULL,
	`o_otherTests9` varchar(150) default NULL,
	`o_otherTests8` varchar(150) default NULL,
	`o_otherTests7` varchar(150) default NULL,
	`o_otherTests6` varchar(150) default NULL,
	`o_specimenCollectionDate` date default NULL,
	`o_otherTests5` varchar(150) default NULL,
	`clinicPC` varchar(10) default NULL,
	`o_otherTests4` varchar(150) default NULL,
	`o_otherTests3` varchar(150) default NULL,
	`o_otherTests2` varchar(150) default NULL,
	`b_cliniciansTelNo` varchar(40) default NULL,
	`o_otherTests1` varchar(150) default NULL,
	`patientName` varchar(40) default NULL,
	`b_dateSigned` date default NULL,
	`practitionerNo` varchar(20) default NULL,
	`m_chlamydia` tinyint(1) default NULL,
	`v_immune_HepatitisC` tinyint(1) default NULL,
	`v_immune_HepatitisB` tinyint(1) default NULL,
	`v_immune_HepatitisA` tinyint(1) default NULL,
        `patientChartNo` varchar(20),
	PRIMARY KEY  (`ID`)
) ;

CREATE TABLE `formRourke2009` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `demographic_no` int(10) ,
  `provider_no` varchar(6) ,
  `formCreated` date ,
  `formEdited` timestamp, 
  `c_lastVisited` char(3) ,
  `c_birthRemarks` text,
  `c_riskFactors` text,
  `c_famHistory` text,
  `c_pName` varchar(60) ,
  `c_birthDate` date ,
  `c_length` varchar(6) ,
  `c_headCirc` varchar(6) ,
  `c_birthWeight` varchar(7) ,
  `c_dischargeWeight` varchar(7) ,
  `c_fsa` char(3) ,
  `c_APGAR1min` int(11) ,
  `c_APGAR5min` int(11) ,
  `p1_2ndhandsmoke` tinyint(1) ,
  `p1_alcohol` tinyint(1) ,
  `p1_drugs` tinyint(1) ,
  `p1_birthRemarksr1` tinyint(1) ,
  `p1_birthRemarksr2` tinyint(1) ,
  `p1_birthRemarksr3` tinyint(1) ,
  `p1_date1w` date ,
  `p1_date2w` date ,
  `p1_date1m` date ,
  `p1_ht1w` varchar(5) ,
  `p1_wt1w` varchar(5) ,
  `p1_hc1w` varchar(5) ,
  `p1_ht2w` varchar(5) ,
  `p1_wt2w` varchar(5) ,
  `p1_hc2w` varchar(5) ,
  `p1_ht1m` varchar(5) ,
  `p1_wt1m` varchar(5) ,
  `p1_hc1m` varchar(5) ,
  `p1_pConcern1w` text,
  `p1_pConcern2w` text,
  `p1_pConcern1m` text,
  `p1_breastFeeding1wOk` tinyint(1) ,
  `p1_breastFeeding1wOkConcerns` tinyint(1) ,
  `p1_formulaFeeding1wOk` tinyint(1) ,
  `p1_formulaFeeding1wOkConcerns` tinyint(1) ,
  `p1_stoolUrine1wOk` tinyint(1) ,
  `p1_stoolUrine1wOkConcerns` tinyint(1) ,
  `p1_breastFeeding2wOk` tinyint(1) ,
  `p1_breastFeeding2wOkConcerns` tinyint(1) ,
  `p1_formulaFeeding2wOk` tinyint(1) ,
  `p1_formulaFeeding2wOkConcerns` tinyint(1) ,
  `p1_stoolUrine2wOk` tinyint(1) ,
  `p1_stoolUrine2wOkConcerns` tinyint(1) ,
  `p1_breastFeeding1mOk` tinyint(1) ,
  `p1_breastFeeding1mOkConcerns` tinyint(1) ,
  `p1_formulaFeeding1mOk` tinyint(1) ,
  `p1_formulaFeeding1mOkConcerns` tinyint(1) ,
  `p1_stoolUrine1mOk` tinyint(1) ,
  `p1_stoolUrine1mOkConcerns` tinyint(1) ,
  `p1_carSeatOk` tinyint(1) ,
  `p1_carSeatOkConcerns` tinyint(1) ,
  `p1_sleepPosOk` tinyint(1) ,
  `p1_sleepPosOkConcerns` tinyint(1) ,
  `p1_cribSafetyOk` tinyint(1) ,
  `p1_cribSafetyOkConcerns` tinyint(1) ,
  `p1_firearmSafetyOk` tinyint(1) ,
  `p1_firearmSafetyOkConcerns` tinyint(1) ,
  `p1_smokeSafetyOk` tinyint(1) ,
  `p1_smokeSafetyOkConcerns` tinyint(1) ,
  `p1_hotWaterOk` tinyint(1) ,
  `p1_hotWaterOkConcerns` tinyint(1) ,
  `p1_safeToysOk` tinyint(1) ,
  `p1_safeToysOkConcerns` tinyint(1) ,
  `p1_sleepCryOk` tinyint(1) ,
  `p1_sleepCryOkConcerns` tinyint(1) ,
  `p1_soothabilityOk` tinyint(1) ,
  `p1_soothabilityOkConcerns` tinyint(1) ,
  `p1_homeVisitOk` tinyint(1) ,
  `p1_homeVisitOkConcerns` tinyint(1) ,
  `p1_bondingOk` tinyint(1) ,
  `p1_bondingOkConcerns` tinyint(1) ,
  `p1_pFatigueOk` tinyint(1) ,
  `p1_pFatigueOkConcerns` tinyint(1) ,
  `p1_famConflictOk` tinyint(1) ,
  `p1_famConflictOkConcerns` tinyint(1) ,
  `p1_siblingsOk` tinyint(1) ,
  `p1_siblingsOkConcerns` tinyint(1) ,
  `p1_2ndSmokeOk` tinyint(1) ,
  `p1_2ndSmokeOkConcerns` tinyint(1) ,
  `p1_altMedOk` tinyint(1) ,
  `p1_altMedOkConcerns` tinyint(1) ,
  `p1_pacifierOk` tinyint(1) ,
  `p1_pacifierOkConcerns` tinyint(1) ,
  `p1_feverOk` tinyint(1) ,
  `p1_feverOkConcerns` tinyint(1) ,
  `p1_noCoughMedOk` tinyint(1) ,
  `p1_noCoughMedOkConcerns` tinyint(1) ,
  `p1_tmpControlOk` tinyint(1) ,
  `p1_tmpControlOkConcerns` tinyint(1) ,
  `p1_sunExposureOk` tinyint(1) ,
  `p1_sunExposureOkConcerns` tinyint(1) ,
  `p1_development1w` text,
  `p1_development2w` text,
  `p1_sucks2wOk` tinyint(1) ,
  `p1_sucks2wNo` tinyint(1) ,
  `p1_noParentsConcerns2wOk` tinyint(1) ,
  `p1_noParentsConcerns2wNo` tinyint(1) ,
  `p1_development1m` text,
  `p1_focusGaze1mOk` tinyint(1) ,
  `p1_focusGaze1mNo` tinyint(1) ,
  `p1_startles1mOk` tinyint(1) ,
  `p1_startles1mNo` tinyint(1) ,
  `p1_calms1mOk` tinyint(1) ,
  `p1_calms1mNo` tinyint(1) ,
  `p1_sucks1mOk` tinyint(1) ,
  `p1_sucks1mNo` tinyint(1) ,
  `p1_noParentsConcerns1mOk` tinyint(1) ,
  `p1_noParentsConcerns1mNo` tinyint(1) ,
  `p1_skin1wOk` tinyint(1) ,
  `p1_skin1wNo` tinyint(1) ,
  `p1_fontanelles1wOk` tinyint(1) ,
  `p1_fontanelles1wNo` tinyint(1) ,
  `p1_eyes1wOk` tinyint(1) ,
  `p1_eyes1wNo` tinyint(1) ,
  `p1_ears1wOk` tinyint(1) ,
  `p1_ears1wNo` tinyint(1) ,
  `p1_heartLungs1wOk` tinyint(1) ,
  `p1_heartLungs1wNo` tinyint(1) ,
  `p1_umbilicus1wOk` tinyint(1) ,
  `p1_umbilicus1wNo` tinyint(1) ,
  `p1_femoralPulses1wOk` tinyint(1) ,
  `p1_femoralPulses1wNo` tinyint(1) ,
  `p1_hips1wOk` tinyint(1) ,
  `p1_hips1wNo` tinyint(1) ,
  `p1_muscleTone1wOk` tinyint(1) ,
  `p1_muscleTone1wNo` tinyint(1) ,
  `p1_testicles1wOk` tinyint(1) ,
  `p1_testicles1wNo` tinyint(1) ,
  `p1_maleUrinary1wOk` tinyint(1) ,
  `p1_maleUrinary1wNo` tinyint(1) ,
  `p1_skin2wOk` tinyint(1) ,
  `p1_skin2wNo` tinyint(1) ,
  `p1_fontanelles2wOk` tinyint(1) ,
  `p1_fontanelles2wNo` tinyint(1) ,
  `p1_eyes2wOk` tinyint(1) ,
  `p1_eyes2wNo` tinyint(1) ,
  `p1_ears2wOk` tinyint(1) ,
  `p1_ears2wNo` tinyint(1) ,
  `p1_heartLungs2wOk` tinyint(1) ,
  `p1_heartLungs2wNo` tinyint(1) ,
  `p1_umbilicus2wOk` tinyint(1) ,
  `p1_umbilicus2wNo` tinyint(1) ,
  `p1_femoralPulses2wOk` tinyint(1) ,
  `p1_femoralPulses2wNo` tinyint(1) ,
  `p1_hips2wOk` tinyint(1) ,
  `p1_hips2wNo` tinyint(1) ,
  `p1_muscleTone2wOk` tinyint(1) ,
  `p1_muscleTone2wNo` tinyint(1) ,
  `p1_testicles2wOk` tinyint(1) ,
  `p1_testicles2wNo` tinyint(1) ,
  `p1_maleUrinary2wOk` tinyint(1) ,
  `p1_maleUrinary2wNo` tinyint(1) ,
  `p1_skin1mOk` tinyint(1) ,
  `p1_skin1mNo` tinyint(1) ,
  `p1_fontanelles1mOk` tinyint(1) ,
  `p1_fontanelles1mNo` tinyint(1) ,
  `p1_eyes1mOk` tinyint(1) ,
  `p1_eyes1mNo` tinyint(1) ,
  `p1_corneal1mOk` tinyint(1) ,
  `p1_corneal1mNo` tinyint(1) ,
  `p1_hearing1mOk` tinyint(1) ,
  `p1_hearing1mNo` tinyint(1) ,
  `p1_heart1mOk` tinyint(1) ,
  `p1_heart1mNo` tinyint(1) ,
  `p1_hips1mOk` tinyint(1) ,
  `p1_hips1mNo` tinyint(1) ,
  `p1_muscleTone1mOk` tinyint(1) ,
  `p1_muscleTone1mNo` tinyint(1) ,
  `p1_pkuThyroid1wOkConcerns` tinyint(1) ,
  `p1_hemoScreen1wOkConcerns` tinyint(1) ,
  `p1_problems1w` text,
  `p1_problems2w` text,
  `p1_problems1m` text,
  `p1_hepatitisVaccine1wOk` tinyint(1) ,
  `p1_hepatitisVaccine1mOk` tinyint(1) ,
  `p1_signature2w` varchar(250) ,
  `p2_date2m` date ,
  `p2_date4m` date ,
  `p2_date6m` date ,
  `p2_ht2m` varchar(5) ,
  `p2_wt2m` varchar(5) ,
  `p2_hc2m` varchar(5) ,
  `p2_ht4m` varchar(5) ,
  `p2_wt4m` varchar(5) ,
  `p2_hc4m` varchar(5) ,
  `p2_ht6m` varchar(5) ,
  `p2_wt6m` varchar(5) ,
  `p2_hc6m` varchar(5) ,
  `p2_pConcern2m` text,
  `p2_pConcern4m` text,
  `p2_pConcern6m` text,
  `p2_nutrition2m` text,
  `p2_breastFeeding2mOk` tinyint(1) ,
  `p2_breastFeeding2mOkConcerns` tinyint(1) ,
  `p2_formulaFeeding2mOk` tinyint(1) ,
  `p2_formulaFeeding2mOkConcerns` tinyint(1) ,
  `p2_nutrition4m` text,
  `p2_breastFeeding4mOk` tinyint(1) ,
  `p2_breastFeeding4mOkConcerns` tinyint(1) ,
  `p2_formulaFeeding4mOk` tinyint(1) ,
  `p2_formulaFeeding4mOkConcerns` tinyint(1) ,
  `p2_breastFeeding6mOk` tinyint(1) ,
  `p2_breastFeeding6mOkConcerns` tinyint(1) ,
  `p2_formulaFeeding6mOk` tinyint(1) ,
  `p2_formulaFeeding6mOkConcerns` tinyint(1) ,
  `p2_bottle6mOk` tinyint(1) ,
  `p2_bottle6mOkConcerns` tinyint(1) ,
  `p2_liquids6mOk` tinyint(1) ,
  `p2_liquids6mOkConcerns` tinyint(1) ,
  `p2_iron6mOk` tinyint(1) ,
  `p2_iron6mOkConcerns` tinyint(1) ,
  `p2_vegFruit6mOk` tinyint(1) ,
  `p2_vegFruit6mOkConcerns` tinyint(1) ,
  `p2_egg6mOk` tinyint(1) ,
  `p2_egg6mOkConcerns` tinyint(1) ,
  `p2_choking6mOk` tinyint(1) ,
  `p2_choking6mOkConcerns` tinyint(1) ,
  `p2_carSeatOk` tinyint(1) ,
  `p2_carSeatOkConcerns` tinyint(1) ,
  `p2_sleepPosOk` tinyint(1) ,
  `p2_sleepPosOkConcerns` tinyint(1) ,
  `p2_poisonsOk` tinyint(1) ,
  `p2_poisonsOkConcerns` tinyint(1) ,
  `p2_firearmSafetyOk` tinyint(1) ,
  `p2_firearmSafetyOkConcerns` tinyint(1) ,
  `p2_electricOk` tinyint(1) ,
  `p2_electricOkConcerns` tinyint(1) ,
  `p2_smokeSafetyOk` tinyint(1) ,
  `p2_smokeSafetyOkConcerns` tinyint(1) ,
  `p2_hotWaterOk` tinyint(1) ,
  `p2_hotWaterOkConcerns` tinyint(1) ,
  `p2_fallsOk` tinyint(1) ,
  `p2_fallsOkConcerns` tinyint(1) ,
  `p2_safeToysOk` tinyint(1) ,
  `p2_safeToysOkConcerns` tinyint(1) ,
  `p2_sleepCryOk` tinyint(1) ,
  `p2_sleepCryOkConcerns` tinyint(1) ,
  `p2_soothabilityOk` tinyint(1) ,
  `p2_soothabilityOkConcerns` tinyint(1) ,
  `p2_homeVisitOk` tinyint(1) ,
  `p2_homeVisitOkConcerns` tinyint(1) ,
  `p2_bondingOk` tinyint(1) ,
  `p2_bondingOkConcerns` tinyint(1) ,
  `p2_pFatigueOk` tinyint(1) ,
  `p2_pFatigueOkConcerns` tinyint(1) ,
  `p2_famConflictOk` tinyint(1) ,
  `p2_famConflictOkConcerns` tinyint(1) ,
  `p2_siblingsOk` tinyint(1) ,
  `p2_siblingsOkConcerns` tinyint(1) ,
  `p2_childCareOk` tinyint(1) ,
  `p2_childCareOkConcerns` tinyint(1) ,
  `p2_2ndSmokeOk` tinyint(1) ,
  `p2_2ndSmokeOkConcerns` tinyint(1) ,
  `p2_teethingOk` tinyint(1) ,
  `p2_teethingOkConcerns` tinyint(1) ,
  `p2_altMedOk` tinyint(1) ,
  `p2_altMedOkConcerns` tinyint(1) ,
  `p2_pacifierOk` tinyint(1) ,
  `p2_pacifierOkConcerns` tinyint(1) ,
  `p2_tmpControlOk` tinyint(1) ,
  `p2_tmpControlOkConcerns` tinyint(1) ,
  `p2_feverOk` tinyint(1) ,
  `p2_feverOkConcerns` tinyint(1) ,
  `p2_sunExposureOk` tinyint(1) ,
  `p2_sunExposureOkConcerns` tinyint(1) ,
  `p2_pesticidesOk` tinyint(1) ,
  `p2_pesticidesOkConcerns` tinyint(1) ,
  `p2_readingOk` tinyint(1) ,
  `p2_readingOkConcerns` tinyint(1) ,
  `p2_noCoughMedOk` tinyint(1) ,
  `p2_noCoughMedOkConcerns` tinyint(1) ,
  `p2_development2m` text,
  `p2_eyesOk` tinyint(1) ,
  `p2_eyesOkConcerns` tinyint(1) ,
  `p2_coosOk` tinyint(1) ,
  `p2_coosOkConcerns` tinyint(1) ,
  `p2_respondsOk` tinyint(1) ,
  `p2_respondsOkConcerns` tinyint(1) ,
  `p2_headUpTummyOk` tinyint(1) ,
  `p2_headUpTummyOkConcerns` tinyint(1) ,
  `p2_cuddledOk` tinyint(1) ,
  `p2_cuddledOkConcerns` tinyint(1) ,
  `p2_2sucksOk` tinyint(1) ,
  `p2_2sucksOkConcerns` tinyint(1) ,
  `p2_smilesOk` tinyint(1) ,
  `p2_smilesOkConcerns` tinyint(1) ,
  `p2_noParentsConcerns2mOk` tinyint(1) ,
  `p2_noParentsConcerns2mOkConcerns` tinyint(1) ,
  `p2_development4m` text,
  `p2_turnsHeadOk` tinyint(1) ,
  `p2_turnsHeadOkConcerns` tinyint(1) ,
  `p2_laughsOk` tinyint(1) ,
  `p2_laughsOkConcerns` tinyint(1) ,
  `p2_headSteadyOk` tinyint(1) ,
  `p2_headSteadyOkConcerns` tinyint(1) ,
  `p2_holdsObjOk` tinyint(1) ,
  `p2_holdsObjOkConcerns` tinyint(1) ,
  `p2_noParentsConcerns4mOk` tinyint(1) ,
  `p2_noParentsConcerns4mOkConcerns` tinyint(1) ,
  `p2_development6m` text,
  `p2_movingObjOk` tinyint(1) ,
  `p2_movingObjOkConcerns` tinyint(1) ,
  `p2_vocalizesOk` tinyint(1) ,
  `p2_vocalizesOkConcerns` tinyint(1) ,
  `p2_makesSoundOk` tinyint(1) ,
  `p2_makesSoundOkConcerns` tinyint(1) ,
  `p2_rollsOk` tinyint(1) ,
  `p2_rollsOkConcerns` tinyint(1) ,
  `p2_sitsOk` tinyint(1) ,
  `p2_sitsOkConcerns` tinyint(1) ,
  `p2_reachesGraspsOk` tinyint(1) ,
  `p2_reachesGraspsOkConcerns` tinyint(1) ,
  `p2_noParentsConcerns6mOk` tinyint(1) ,
  `p2_noParentsConcerns6mOkConcerns` tinyint(1) ,
  `p2_fontanelles2mOk` tinyint(1) ,
  `p2_fontanelles2mOkConcerns` tinyint(1) ,
  `p2_eyes2mOk` tinyint(1) ,
  `p2_eyes2mOkConcerns` tinyint(1) ,
  `p2_corneal2mOk` tinyint(1) ,
  `p2_corneal2mOkConcerns` tinyint(1) ,
  `p2_hearing2mOk` tinyint(1) ,
  `p2_hearing2mOkConcerns` tinyint(1) ,
  `p2_heart2mOk` tinyint(1) ,
  `p2_heart2mOkConcerns` tinyint(1) ,
  `p2_hips2mOk` tinyint(1) ,
  `p2_hips2mOkConcerns` tinyint(1) ,
  `p2_muscleTone2mOk` tinyint(1) ,
  `p2_muscleTone2mOkConcerns` tinyint(1) ,
  `p2_fontanelles4mOk` tinyint(1) ,
  `p2_fontanelles4mOkConcerns` tinyint(1) ,
  `p2_eyes4mOk` tinyint(1) ,
  `p2_eyes4mOkConcerns` tinyint(1) ,
  `p2_corneal4mOk` tinyint(1) ,
  `p2_corneal4mOkConcerns` tinyint(1) ,
  `p2_hearing4mOk` tinyint(1) ,
  `p2_hearing4mOkConcerns` tinyint(1) ,
  `p2_hips4mOk` tinyint(1) ,
  `p2_hips4mOkConcerns` tinyint(1) ,
  `p2_muscleTone4mOk` tinyint(1) ,
  `p2_muscleTone4mOkConcerns` tinyint(1) ,
  `p2_fontanelles6mOk` tinyint(1) ,
  `p2_fontanelles6mOkConcerns` tinyint(1) ,
  `p2_eyes6mOk` tinyint(1) ,
  `p2_eyes6mOkConcerns` tinyint(1) ,
  `p2_corneal6mOk` tinyint(1) ,
  `p2_corneal6mOkConcerns` tinyint(1) ,
  `p2_hearing6mOk` tinyint(1) ,
  `p2_hearing6mOkConcerns` tinyint(1) ,
  `p2_hips6mOk` tinyint(1) ,
  `p2_hips6mOkConcerns` tinyint(1) ,
  `p2_muscleTone6mOk` tinyint(1) ,
  `p2_muscleTone6mOkConcerns` tinyint(1) ,
  `p2_problems2m` text,
  `p2_problems4m` text,
  `p2_problems6m` text,
  `p2_tb6mOkConcerns` tinyint(1) ,
  `p2_hepatitisVaccine6mOk` tinyint(1) ,
  `p2_signature2m` varchar(250) ,
  `p2_signature4m` varchar(250) ,
  `p3_date9m` date ,
  `p3_date12m` date ,
  `p3_date15m` date ,
  `p3_ht9m` varchar(5) ,
  `p3_wt9m` varchar(5) ,
  `p3_hc9m` varchar(5) ,
  `p3_ht12m` varchar(5) ,
  `p3_wt12m` varchar(5) ,
  `p3_hc12m` varchar(5) ,
  `p3_ht15m` varchar(5) ,
  `p3_wt15m` varchar(5) ,
  `p3_hc15m` varchar(5) ,
  `p3_pConcern9m` text,
  `p3_pConcern12m` text,
  `p3_pConcern15m` text,
  `p3_breastFeeding9mOk` tinyint(1) ,
  `p3_breastFeeding9mOkConcerns` tinyint(1) ,
  `p3_formulaFeeding9mOk` tinyint(1) ,
  `p3_formulaFeeding9mOkConcerns` tinyint(1) ,
  `p3_bottle9mOk` tinyint(1) ,
  `p3_bottle9mOkConcerns` tinyint(1) ,
  `p3_liquids9mOk` tinyint(1) ,
  `p3_liquids9mOkConcerns` tinyint(1) ,
  `p3_cereal9mOk` tinyint(1) ,
  `p3_cereal9mOkConcerns` tinyint(1) ,
  `p3_introCowMilk9mOk` tinyint(1) ,
  `p3_introCowMilk9mOkConcerns` tinyint(1) ,
  `p3_egg9mOk` tinyint(1) ,
  `p3_egg9mOkConcerns` tinyint(1) ,
  `p3_choking9mOk` tinyint(1) ,
  `p3_choking9mOkConcerns` tinyint(1) ,
  `p3_nutrition12m` text,
  `p3_breastFeeding12mOk` tinyint(1) ,
  `p3_breastFeeding12mOkConcerns` tinyint(1) ,
  `p3_homoMilk12mOk` tinyint(1) ,
  `p3_homoMilk12mOkConcerns` tinyint(1) ,
  `p3_cup12mOk` tinyint(1) ,
  `p3_cup12mOkConcerns` tinyint(1) ,
  `p3_appetite12mOk` tinyint(1) ,
  `p3_appetite12mOkConcerns` tinyint(1) ,
  `p3_choking12mOk` tinyint(1) ,
  `p3_choking12mOkConcerns` tinyint(1) ,
  `p3_nutrition15m` text,
  `p3_breastFeeding15mOk` tinyint(1) ,
  `p3_breastFeeding15mOkConcerns` tinyint(1) ,
  `p3_homoMilk15mOk` tinyint(1) ,
  `p3_homoMilk15mOkConcerns` tinyint(1) ,
  `p3_choking15mOk` tinyint(1) ,
  `p3_choking15mOkConcerns` tinyint(1) ,
  `p3_cup15mOk` tinyint(1) ,
  `p3_cup15mOkConcerns` tinyint(1) ,
  `p3_carSeatOk` tinyint(1) ,
  `p3_carSeatOkConcerns` tinyint(1) ,
  `p3_poisonsOk` tinyint(1) ,
  `p3_poisonsOkConcerns` tinyint(1) ,
  `p3_firearmSafetyOk` tinyint(1) ,
  `p3_firearmSafetyOkConcerns` tinyint(1) ,
  `p3_smokeSafetyOk` tinyint(1) ,
  `p3_smokeSafetyOkConcerns` tinyint(1) ,
  `p3_hotWaterOk` tinyint(1) ,
  `p3_hotWaterOkConcerns` tinyint(1) ,
  `p3_electricOk` tinyint(1) ,
  `p3_electricOkConcerns` tinyint(1) ,
  `p3_fallsOk` tinyint(1) ,
  `p3_fallsOkConcerns` tinyint(1) ,
  `p3_safeToysOk` tinyint(1) ,
  `p3_safeToysOkConcerns` tinyint(1) ,
  `p3_sleepCryOk` tinyint(1) ,
  `p3_sleepCryOkConcerns` tinyint(1) ,
  `p3_soothabilityOk` tinyint(1) ,
  `p3_soothabilityOkConcerns` tinyint(1) ,
  `p3_homeVisitOk` tinyint(1) ,
  `p3_homeVisitOkConcerns` tinyint(1) ,
  `p3_parentingOk` tinyint(1) ,
  `p3_parentingOkConcerns` tinyint(1) ,
  `p3_pFatigueOk` tinyint(1) ,
  `p3_pFatigueOkConcerns` tinyint(1) ,
  `p3_famConflictOk` tinyint(1) ,
  `p3_famConflictOkConcerns` tinyint(1) ,
  `p3_siblingsOk` tinyint(1) ,
  `p3_siblingsOkConcerns` tinyint(1) ,
  `p3_childCareOk` tinyint(1) ,
  `p3_childCareOkConcerns` tinyint(1) ,
  `p3_2ndSmokeOk` tinyint(1) ,
  `p3_2ndSmokeOkConcerns` tinyint(1) ,
  `p3_teethingOk` tinyint(1) ,
  `p3_teethingOkConcerns` tinyint(1) ,
  `p3_altMedOk` tinyint(1) ,
  `p3_altMedOkConcerns` tinyint(1) ,
  `p3_pacifierOk` tinyint(1) ,
  `p3_pacifierOkConcerns` tinyint(1) ,
  `p3_feverOk` tinyint(1) ,
  `p3_feverOkConcerns` tinyint(1) ,
  `p3_coughMedOk` tinyint(1) ,
  `p3_coughMedOkConcerns` tinyint(1) ,
  `p3_activeOk` tinyint(1) ,
  `p3_activeOkConcerns` tinyint(1) ,
  `p3_readingOk` tinyint(1) ,
  `p3_readingOkConcerns` tinyint(1) ,
  `p3_footwearOk` tinyint(1) ,
  `p3_footwearOkConcerns` tinyint(1) ,
  `p3_sunExposureOk` tinyint(1) ,
  `p3_sunExposureOkConcerns` tinyint(1) ,
  `p3_checkSerumOk` tinyint(1) ,
  `p3_checkSerumOkConcerns` tinyint(1) ,
  `p3_pesticidesOk` tinyint(1) ,
  `p3_pesticidesOkConcerns` tinyint(1) ,
  `p3_development9m` text,
  `p3_hiddenToyOk` tinyint(1) ,
  `p3_hiddenToyOkConcerns` tinyint(1) ,
  `p3_soundsOk` tinyint(1) ,
  `p3_soundsOkConcerns` tinyint(1) ,
  `p3_responds2peopleOk` tinyint(1) ,
  `p3_responds2peopleOkConcerns` tinyint(1) ,
  `p3_makeSoundsOk` tinyint(1) ,
  `p3_makeSoundsOkConcerns` tinyint(1) ,
  `p3_sitsOk` tinyint(1) ,
  `p3_sitsOkConcerns` tinyint(1) ,
  `p3_standsOk` tinyint(1) ,
  `p3_standsOkConcerns` tinyint(1) ,
  `p3_thumbOk` tinyint(1) ,
  `p3_thumbOkConcerns` tinyint(1) ,
  `p3_playGamesOk` tinyint(1) ,
  `p3_playGamesOkConcerns` tinyint(1) ,
  `p3_attention9mOk` tinyint(1) ,
  `p3_attention9mOkConcerns` tinyint(1) ,
  `p3_noParentsConcerns9mOk` tinyint(1) ,
  `p3_noParentsConcerns9mOkConcerns` tinyint(1) ,
  `p3_development12m` text,
  `p3_respondsOk` tinyint(1) ,
  `p3_respondsOkConcerns` tinyint(1) ,
  `p3_simpleRequestsOk` tinyint(1) ,
  `p3_simpleRequestsOkConcerns` tinyint(1) ,
  `p3_consonantOk` tinyint(1) ,
  `p3_consonantOkConcerns` tinyint(1) ,
  `p3_says3wordsOk` tinyint(1) ,
  `p3_says3wordsOkConcerns` tinyint(1) ,
  `p3_shufflesOk` tinyint(1) ,
  `p3_shufflesOkConcerns` tinyint(1) ,
  `p3_pull2standOk` tinyint(1) ,
  `p3_pull2standOkConcerns` tinyint(1) ,
  `p3_showDistressOk` tinyint(1) ,
  `p3_showDistressOkConcerns` tinyint(1) ,
  `p3_followGazeOk` tinyint(1) ,
  `p3_followGazeOkConcerns` tinyint(1) ,
  `p3_noParentsConcerns12mOk` tinyint(1) ,
  `p3_noParentsConcerns12mOkConcerns` tinyint(1) ,
  `p3_says5wordsOk` tinyint(1) ,
  `p3_says5wordsOkConcerns` tinyint(1) ,
  `p3_reachesOk` tinyint(1) ,
  `p3_reachesNo` tinyint(1) ,
  `p3_fingerFoodsOk` tinyint(1) ,
  `p3_fingerFoodsOkConcerns` tinyint(1) ,
  `p3_walksSidewaysOk` tinyint(1) ,
  `p3_walksSidewaysOkConcerns` tinyint(1) ,
  `p3_showsFearStrangersOk` tinyint(1) ,
  `p3_showsFearStrangersOkConcerns` tinyint(1) ,
  `p3_crawlsStairsOk` tinyint(1) ,
  `p3_crawlsStairsOkConcerns` tinyint(1) ,
  `p3_squatsOk` tinyint(1) ,
  `p3_squatsOkConcerns` tinyint(1) ,
  `p3_noParentsConcerns15mOk` tinyint(1) ,
  `p3_noParentsConcerns15mOkConcerns` tinyint(1) ,
  `p3_fontanelles9mOk` tinyint(1) ,
  `p3_fontanelles9mOkConcerns` tinyint(1) ,
  `p3_eyes9mOk` tinyint(1) ,
  `p3_eyes9mOkConcerns` tinyint(1) ,
  `p3_corneal9mOk` tinyint(1) ,
  `p3_corneal9mOkConcerns` tinyint(1) ,
  `p3_hearing9mOk` tinyint(1) ,
  `p3_hearing9mOkConcerns` tinyint(1) ,
  `p3_hips9mOk` tinyint(1) ,
  `p3_hips9mOkConcerns` tinyint(1) ,
  `p3_fontanelles12mOk` tinyint(1) ,
  `p3_fontanelles12mOkConcerns` tinyint(1) ,
  `p3_eyes12mOk` tinyint(1) ,
  `p3_eyes12mOkConcerns` tinyint(1) ,
  `p3_corneal12mOk` tinyint(1) ,
  `p3_corneal12mOkConcerns` tinyint(1) ,
  `p3_hearing12mOk` tinyint(1) ,
  `p3_hearing12mOkConcerns` tinyint(1) ,
  `p3_tonsil12mOk` tinyint(1) ,
  `p3_tonsil12mOkConcerns` tinyint(1) ,
  `p3_hips12mOk` tinyint(1) ,
  `p3_hips12mOkConcerns` tinyint(1) ,
  `p3_development15m` text,
  `p3_fontanelles15mOk` tinyint(1) ,
  `p3_fontanelles15mOkConcerns` tinyint(1) ,
  `p3_eyes15mOk` tinyint(1) ,
  `p3_eyes15mOkConcerns` tinyint(1) ,
  `p3_corneal15mOk` tinyint(1) ,
  `p3_corneal15mOkConcerns` tinyint(1) ,
  `p3_hearing15mOk` tinyint(1) ,
  `p3_hearing15mOkConcerns` tinyint(1) ,
  `p3_tonsil15mOk` tinyint(1) ,
  `p3_tonsil15mOkConcerns` tinyint(1) ,
  `p3_hips15mOk` tinyint(1) ,
  `p3_hips15mOkConcerns` tinyint(1) ,
  `p3_problems9m` text,
  `p3_problems12m` text,
  `p3_problems15m` text,
  `p3_antiHB9mOkConcerns` tinyint(1) ,
  `p3_hemoglobin9mOkConcerns` tinyint(1) ,
  `p3_hemoglobin12mOkConcerns` tinyint(1) ,
  `p3_signature9m` varchar(250) ,
  `p3_signature12m` varchar(250) ,
  `p3_signature15m` varchar(250) ,
  `p4_date18m` date ,
  `p4_date24m` date ,
  `p4_date48m` date ,
  `p4_ht18m` varchar(5) ,
  `p4_wt18m` varchar(5) ,
  `p4_hc18m` varchar(5) ,
  `p4_ht24m` varchar(5) ,
  `p4_wt24m` varchar(5) ,
  `p4_hc24m` varchar(5) ,
  `p4_ht48m` varchar(5) ,
  `p4_wt48m` varchar(5) ,
  `p4_pConcern18m` text,
  `p4_pConcern24m` text,
  `p4_pConcern48m` text,
  `p4_breastFeeding18mOk` tinyint(1) ,
  `p4_breastFeeding18mOkConcerns` tinyint(1) ,
  `p4_homoMilk18mOk` tinyint(1) ,
  `p4_homoMilk18mOkConcerns` tinyint(1) ,
  `p4_bottle18mOk` tinyint(1) ,
  `p4_bottle18mOkConcerns` tinyint(1) ,
  `p4_homo2percent24mOk` tinyint(1) ,
  `p4_homo2percent24mOkConcerns` tinyint(1) ,
  `p4_lowerfatdiet24mOk` tinyint(1) ,
  `p4_lowerfatdiet24mOkConcerns` tinyint(1) ,
  `p4_foodguide24mOk` tinyint(1) ,
  `p4_foodguide24mNo` tinyint(1) ,
  `p4_2pMilk48mOk` tinyint(1) ,
  `p4_2pMilk48mOkConcerns` tinyint(1) ,
  `p4_foodguide48mOk` tinyint(1) ,
  `p4_foodguide48mNo` tinyint(1) ,
  `p4_carSeat18mOk` tinyint(1) ,
  `p4_carSeat18mOkConcerns` tinyint(1) ,
  `p4_bathSafetyOk` tinyint(1) ,
  `p4_bathSafetyOkConcerns` tinyint(1) ,
  `p4_safeToysOk` tinyint(1) ,
  `p4_safeToysOkConcerns` tinyint(1) ,
  `p4_parentChild18mOk` tinyint(1) ,
  `p4_parentChild18mOkConcerns` tinyint(1) ,
  `p4_discipline18mOk` tinyint(1) ,
  `p4_discipline18mOkConcerns` tinyint(1) ,
  `p4_pFatigue18mOk` tinyint(1) ,
  `p4_pFatigue18mOkConcerns` tinyint(1) ,
  `p4_highRisk18mOk` tinyint(1) ,
  `p4_highRisk18mOkConcerns` tinyint(1) ,
  `p4_socializing18mOk` tinyint(1) ,
  `p4_socializing18mOkConcerns` tinyint(1) ,
  `p4_weanPacifier18mOk` tinyint(1) ,
  `p4_weanPacifier18mOkConcerns` tinyint(1) ,
  `p4_dentalCareOk` tinyint(1) ,
  `p4_dentalCareOkConcerns` tinyint(1) ,
  `p4_toiletLearning18mOk` tinyint(1) ,
  `p4_toiletLearning18mOkConcerns` tinyint(1) ,
  `p4_encourageReading18mOk` tinyint(1) ,
  `p4_encourageReading18mOkConcerns` tinyint(1) ,
  `p4_carSeat24mOk` tinyint(1) ,
  `p4_carSeat24mOkConcerns` tinyint(1) ,
  `p4_bikeHelmetsOk` tinyint(1) ,
  `p4_bikeHelmetsOkConcerns` tinyint(1) ,
  `p4_firearmSafetyOk` tinyint(1) ,
  `p4_firearmSafetyOkConcerns` tinyint(1) ,
  `p4_smokeSafetyOk` tinyint(1) ,
  `p4_smokeSafetyOkConcerns` tinyint(1) ,
  `p4_matchesOk` tinyint(1) ,
  `p4_matchesOkConcerns` tinyint(1) ,
  `p4_waterSafetyOk` tinyint(1) ,
  `p4_waterSafetyOkConcerns` tinyint(1) ,
  `p4_parentChild24mOk` tinyint(1) ,
  `p4_parentChild24mOkConcerns` tinyint(1) ,
  `p4_discipline24mOk` tinyint(1) ,
  `p4_discipline24mOkConcerns` tinyint(1) ,
  `p4_highRisk24mOk` tinyint(1) ,
  `p4_highRisk24mOkConcerns` tinyint(1) ,
  `p4_pFatigue24mOk` tinyint(1) ,
  `p4_pFatigue24mOkConcerns` tinyint(1) ,
  `p4_famConflictOk` tinyint(1) ,
  `p4_famConflictOkConcerns` tinyint(1) ,
  `p4_siblingsOk` tinyint(1) ,
  `p4_siblingsOkConcerns` tinyint(1) ,
  `p4_2ndSmokeOk` tinyint(1) ,
  `p4_2ndSmokeOkConcerns` tinyint(1) ,
  `p4_dentalCleaningOk` tinyint(1) ,
  `p4_dentalCleaningOkConcerns` tinyint(1) ,
  `p4_altMedOk` tinyint(1) ,
  `p4_altMedOkConcerns` tinyint(1) ,
  `p4_toiletLearning24mOk` tinyint(1) ,
  `p4_toiletLearning24mOkConcerns` tinyint(1) ,
  `p4_activeOk` tinyint(1) ,
  `p4_activeOkConcerns` tinyint(1) ,
  `p4_socializing24mOk` tinyint(1) ,
  `p4_socializing24mOkConcerns` tinyint(1) ,
  `p4_readingOk` tinyint(1) ,
  `p4_readingOkConcerns` tinyint(1) ,
  `p4_noCough24mOk` tinyint(1) ,
  `p4_noCough24mOkConcerns` tinyint(1) ,
  `p4_noPacifier24mOk` tinyint(1) ,
  `p4_noPacifier24mOkConcerns` tinyint(1) ,
  `p4_dayCareOk` tinyint(1) ,
  `p4_dayCareOkConcerns` tinyint(1) ,
  `p4_sunExposureOk` tinyint(1) ,
  `p4_sunExposureOkConcerns` tinyint(1) ,
  `p4_pesticidesOk` tinyint(1) ,
  `p4_pesticidesOkConcerns` tinyint(1) ,
  `p4_checkSerumOk` tinyint(1) ,
  `p4_checkSerumOkConcerns` tinyint(1) ,
  `p4_manageableOk` tinyint(1) ,
  `p4_manageableOkConcerns` tinyint(1) ,
  `p4_otherChildrenOkConcerns` tinyint(1) ,
  `p4_otherChildrenOk` tinyint(1) ,
  `p4_soothabilityOk` tinyint(1) ,
  `p4_soothabilityOkConcerns` tinyint(1) ,
  `p4_comfortOk` tinyint(1) ,
  `p4_comfortOkConcerns` tinyint(1) ,
  `p4_pointsOk` tinyint(1) ,
  `p4_pointsOkConcerns` tinyint(1) ,
  `p4_getAttnOk` tinyint(1) ,
  `p4_getAttnOkConcerns` tinyint(1) ,
  `p4_points2wantOk` tinyint(1) ,
  `p4_points2wantOkConcerns` tinyint(1) ,
  `p4_looks4toyOk` tinyint(1) ,
  `p4_looks4toyOkConcerns` tinyint(1) ,
  `p4_recsNameOk` tinyint(1) ,
  `p4_recsNameOkConcerns` tinyint(1) ,
  `p4_initSpeechOk` tinyint(1) ,
  `p4_initSpeechOkConcerns` tinyint(1) ,
  `p4_says20wordsOk` tinyint(1) ,
  `p4_says20wordsOkConcerns` tinyint(1) ,
  `p4_4consonantsOk` tinyint(1) ,
  `p4_4consonantsOkConcerns` tinyint(1) ,
  `p4_walksbackOk` tinyint(1) ,
  `p4_walksbackOkConcerns` tinyint(1) ,
  `p4_feedsSelfOk` tinyint(1) ,
  `p4_feedsSelfOkConcerns` tinyint(1) ,
  `p4_removesHatOk` tinyint(1) ,
  `p4_removesHatOkConcerns` tinyint(1) ,
  `p4_noParentsConcerns18mOk` tinyint(1) ,
  `p4_noParentsConcerns18mOkConcerns` tinyint(1) ,
  `p4_2wSentenceOk` tinyint(1) ,
  `p4_2wSentenceOkConcerns` tinyint(1) ,
  `p4_one2stepdirectionsOk` tinyint(1) ,
  `p4_one2stepdirectionsOkConcerns` tinyint(1) ,
  `p4_walksbackwardOk` tinyint(1) ,
  `p4_walksbackwardOkConcerns` tinyint(1) ,
  `p4_runsOk` tinyint(1) ,
  `p4_runsOkConcerns` tinyint(1) ,
  `p4_smallContainerOk` tinyint(1) ,
  `p4_smallContainerOkConcerns` tinyint(1) ,
  `p4_pretendsPlayOk` tinyint(1) ,
  `p4_pretendsPlayOkConcerns` tinyint(1) ,
  `p4_newSkillsOk` tinyint(1) ,
  `p4_newSkillsOkConcerns` tinyint(1) ,
  `p4_noParentsConcerns24mOk` tinyint(1) ,
  `p4_noParentsConcerns24mOkConcerns` tinyint(1) ,
  `p4_3directionsOk` tinyint(1) ,
  `p4_3directionsOkConcerns` tinyint(1) ,
  `p4_asksQuestionsOk` tinyint(1) ,
  `p4_asksQuestionsOkConcerns` tinyint(1) ,
  `p4_upDownStairsOk` tinyint(1) ,
  `p4_upDownStairsOkConcerns` tinyint(1) ,
  `p4_undoesZippersOk` tinyint(1) ,
  `p4_undoesZippersOkConcerns` tinyint(1) ,
  `p4_tries2comfortOk` tinyint(1) ,
  `p4_tries2comfortOkConcerns` tinyint(1) ,
  `p4_noParentsConcerns48mOk` tinyint(1) ,
  `p4_noParentsConcerns48mOkConcerns` tinyint(1) ,
  `p4_2directionsOk` tinyint(1) ,
  `p4_2directionsOkConcerns` tinyint(1) ,
  `p4_5ormoreWordsOk` tinyint(1) ,
  `p4_5ormoreWordsOkConcerns` tinyint(1) ,
  `p4_walksUpStairsOk` tinyint(1) ,
  `p4_walksUpStairsOkConcerns` tinyint(1) ,
  `p4_twistslidsOk` tinyint(1) ,
  `p4_twistslidsOkConcerns` tinyint(1) ,
  `p4_turnsPagesOk` tinyint(1) ,
  `p4_turnsPagesOkConcerns` tinyint(1) ,
  `p4_sharesSometimeOk` tinyint(1) ,
  `p4_sharesSometimeOkConcerns` tinyint(1) ,
  `p4_playMakeBelieveOk` tinyint(1) ,
  `p4_playMakeBelieveOkConcerns` tinyint(1) ,
  `p4_listenMusikOk` tinyint(1) ,
  `p4_listenMusikOkConcerns` tinyint(1) ,
  `p4_noParentsConcerns36mOk` tinyint(1) ,
  `p4_noParentsConcerns36mOkConcerns` tinyint(1) ,
  `p4_countsOutloudOk` tinyint(1) ,
  `p4_countsOutloudOkConcerns` tinyint(1) ,
  `p4_speaksClearlyOk` tinyint(1) ,
  `p4_speaksClearlyOkConcerns` tinyint(1) ,
  `p4_throwsCatchesOk` tinyint(1) ,
  `p4_throwsCatchesOkConcerns` tinyint(1) ,
  `p4_hops1footOk` tinyint(1) ,
  `p4_hops1footOkConcerns` tinyint(1) ,
  `p4_dressesUndressesOk` tinyint(1) ,
  `p4_dressesUndressesOkConcerns` tinyint(1) ,
  `p4_obeysAdultOk` tinyint(1) ,
  `p4_obeysAdultOkConcerns` tinyint(1) ,
  `p4_retellsStoryOk` tinyint(1) ,
  `p4_retellsStoryOkConcerns` tinyint(1) ,
  `p4_separatesOk` tinyint(1) ,
  `p4_separatesOkConcerns` tinyint(1) ,
  `p4_noParentsConcerns60mOk` tinyint(1) ,
  `p4_noParentsConcerns60mOkConcerns` tinyint(1) ,
  `p4_fontanellesClosedOk` tinyint(1) ,
  `p4_fontanellesClosedOkConcerns` tinyint(1) ,
  `p4_eyes18mOk` tinyint(1) ,
  `p4_eyes18mOkConcerns` tinyint(1) ,
  `p4_corneal18mOk` tinyint(1) ,
  `p4_corneal18mOkConcerns` tinyint(1) ,
  `p4_hearing18mOk` tinyint(1) ,
  `p4_hearing18mOkConcerns` tinyint(1) ,
  `p4_tonsil18mOk` tinyint(1) ,
  `p4_tonsil18mOkConcerns` tinyint(1) ,
  `p4_bloodpressure24mOk` tinyint(1) ,
  `p4_bloodpressure24mOkConcerns` tinyint(1) ,
  `p4_eyes24mOk` tinyint(1) ,
  `p4_eyes24mOkConcerns` tinyint(1) ,
  `p4_corneal24mOk` tinyint(1) ,
  `p4_corneal24mOkConcerns` tinyint(1) ,
  `p4_hearing24mOk` tinyint(1) ,
  `p4_hearing24mOkConcerns` tinyint(1) ,
  `p4_tonsil24mOk` tinyint(1) ,
  `p4_tonsil24mOkConcerns` tinyint(1) ,
  `p4_bloodpressure48mOk` tinyint(1) ,
  `p4_bloodpressure48mOkConcerns` tinyint(1) ,
  `p4_eyes48mOk` tinyint(1) ,
  `p4_eyes48mOkConcerns` tinyint(1) ,
  `p4_corneal48mOk` tinyint(1) ,
  `p4_corneal48mOkConcerns` tinyint(1) ,
  `p4_hearing48mOk` tinyint(1) ,
  `p4_hearing48mOkConcerns` tinyint(1) ,
  `p4_tonsil48mOk` tinyint(1) ,
  `p4_tonsil48mOkConcerns` tinyint(1) ,
  `p4_problems18m` text,
  `p4_problems24m` text,
  `p4_problems48m` text,
  `p4_signature18m` varchar(250) ,
  `p4_signature24m` varchar(250) ,
  `p4_signature48m` varchar(250) ,
  `p1_signature1w` varchar(250) ,
  `p1_signature1m` varchar(250) ,
  `p2_signature6m` varchar(250) ,
  `p1_breastFeeding1wNo` tinyint(1) ,
  `p1_breastFeeding1wNotDiscussed` tinyint(1) ,
  `p1_formulaFeeding1wNo` tinyint(1) ,
  `p1_formulaFeeding1wNotDiscussed` tinyint(1) ,
  `p1_stoolUrine1wNotDiscussed` tinyint(1) ,
  `p1_breastFeeding2wNo` tinyint(1) ,
  `p1_breastFeeding2wNotDiscussed` tinyint(1) ,
  `p1_formulaFeeding2wNo` tinyint(1) ,
  `p1_formulaFeeding2wNotDiscussed` tinyint(1) ,
  `p1_stoolUrine2wNotDiscussed` tinyint(1) ,
  `p1_breastFeeding1mNo` tinyint(1) ,
  `p1_breastFeeding1mNotDiscussed` tinyint(1) ,
  `p1_formulaFeeding1mNo` tinyint(1) ,
  `p1_formulaFeeding1mNotDiscussed` tinyint(1) ,
  `p1_stoolUrine1mNotDiscussed` tinyint(1) ,
  `p1_carSeatNotDiscussed` tinyint(1) ,
  `p1_sleepPosNotDiscussed` tinyint(1) ,
  `p1_cribSafetyNotDiscussed` tinyint(1) ,
  `p1_firearmSafetyNotDiscussed` tinyint(1) ,
  `p1_smokeSafetyNotDiscussed` tinyint(1) ,
  `p1_hotWaterNotDiscussed` tinyint(1) ,
  `p1_safeToysNotDiscussed` tinyint(1) ,
  `p1_sleepCryNotDiscussed` tinyint(1) ,
  `p1_soothabilityNotDiscussed` tinyint(1) ,
  `p1_bondingNotDiscussed` tinyint(1) ,
  `p1_pFatigueNotDiscussed` tinyint(1) ,
  `p1_famConflictNotDiscussed` tinyint(1) ,
  `p1_siblingsNotDiscussed` tinyint(1) ,
  `p1_homeVisitNotDiscussed` tinyint(1) ,
  `p1_2ndSmokeNotDiscussed` tinyint(1) ,
  `p1_altMedNotDiscussed` tinyint(1) ,
  `p1_pacifierNotDiscussed` tinyint(1) ,
  `p1_feverNotDiscussed` tinyint(1) ,
  `p1_tmpControlNotDiscussed` tinyint(1) ,
  `p1_sunExposureNotDiscussed` tinyint(1) ,
  `p1_noCoughMedNotDiscussed` tinyint(1) ,
  `p1_sucks2wNotDiscussed` tinyint(1) ,
  `p1_noParentsConcerns2wNotDiscussed` tinyint(1) ,
  `p1_focusGaze1mNotDiscussed` tinyint(1) ,
  `p1_startles1mNotDiscussed` tinyint(1) ,
  `p1_calms1mNotDiscussed` tinyint(1) ,
  `p1_sucks1mNotDiscussed` tinyint(1) ,
  `p1_noParentsConcerns1mNotDiscussed` tinyint(1) ,
  `p1_skin1wNotDiscussed` tinyint(1) ,
  `p1_fontanelles1wNotDiscussed` tinyint(1) ,
  `p1_eyes1wNotDiscussed` tinyint(1) ,
  `p1_ears1wNotDiscussed` tinyint(1) ,
  `p1_heartLungs1wNotDiscussed` tinyint(1) ,
  `p1_umbilicus1wNotDiscussed` tinyint(1) ,
  `p1_femoralPulses1wNotDiscussed` tinyint(1) ,
  `p1_hips1wNotDiscussed` tinyint(1) ,
  `p1_muscleTone1wNotDiscussed` tinyint(1) ,
  `p1_testicles1wNotDiscussed` tinyint(1) ,
  `p1_maleUrinary1wNotDiscussed` tinyint(1) ,
  `p1_skin2wNotDiscussed` tinyint(1) ,
  `p1_fontanelles2wNotDiscussed` tinyint(1) ,
  `p1_eyes2wNotDiscussed` tinyint(1) ,
  `p1_ears2wNotDiscussed` tinyint(1) ,
  `p1_heartLungs2wNotDiscussed` tinyint(1) ,
  `p1_umbilicus2wNotDiscussed` tinyint(1) ,
  `p1_femoralPulses2wNotDiscussed` tinyint(1) ,
  `p1_hips2wNotDiscussed` tinyint(1) ,
  `p1_muscleTone2wNotDiscussed` tinyint(1) ,
  `p1_testicles2wNotDiscussed` tinyint(1) ,
  `p1_maleUrinary2wNotDiscussed` tinyint(1) ,
  `p1_skin1mNotDiscussed` tinyint(1) ,
  `p1_fontanelles1mNotDiscussed` tinyint(1) ,
  `p1_eyes1mNotDiscussed` tinyint(1) ,
  `p1_corneal1mNotDiscussed` tinyint(1) ,
  `p1_hearing1mNotDiscussed` tinyint(1) ,
  `p1_heart1mNotDiscussed` tinyint(1) ,
  `p1_hips1mNotDiscussed` tinyint(1) ,
  `p1_muscleTone1mNotDiscussed` tinyint(1) ,
  `p1_pkuThyroid1wOk` tinyint(1) ,
  `p1_pkuThyroid1wNotDiscussed` tinyint(1) ,
  `p1_hemoScreen1wOk` tinyint(1) ,
  `p1_hemoScreen1wNotDiscussed` tinyint(1) ,
  `p1_hepatitisVaccine1wNo` tinyint(1) ,
  `p1_hepatitisVaccine1mNo` tinyint(1) ,
  `p2_breastFeeding2mNo` tinyint(1) ,
  `p2_breastFeeding2mNotDiscussed` tinyint(1) ,
  `p2_formulaFeeding2mNo` tinyint(1) ,
  `p2_formulaFeeding2mNotDiscussed` tinyint(1) ,
  `p2_breastFeeding4mNo` tinyint(1) ,
  `p2_breastFeeding4mNotDiscussed` tinyint(1) ,
  `p2_formulaFeeding4mNo` tinyint(1) ,
  `p2_formulaFeeding4mNotDiscussed` tinyint(1) ,
  `p2_breastFeeding6mNo` tinyint(1) ,
  `p2_breastFeeding6mNotDiscussed` tinyint(1) ,
  `p2_formulaFeeding6mNo` tinyint(1) ,
  `p2_formulaFeeding6mNotDiscussed` tinyint(1) ,
  `p2_bottle6mNotDiscussed` tinyint(1) ,
  `p2_liquids6mNo` tinyint(1) ,
  `p2_liquids6mNotDiscussed` tinyint(1) ,
  `p2_iron6mNotDiscussed` tinyint(1) ,
  `p2_vegFruit6mNotDiscussed` tinyint(1) ,
  `p2_egg6mNotDiscussed` tinyint(1) ,
  `p2_choking6mNotDiscussed` tinyint(1) ,
  `p2_carSeatNotDiscussed` tinyint(1) ,
  `p2_sleepPosNotDiscussed` tinyint(1) ,
  `p2_poisonsNotDiscussed` tinyint(1) ,
  `p2_firearmSafetyNotDiscussed` tinyint(1) ,
  `p2_electricNotDiscussed` tinyint(1) ,
  `p2_smokeSafetyNotDiscussed` tinyint(1) ,
  `p2_hotWaterNotDiscussed` tinyint(1) ,
  `p2_fallsNotDiscussed` tinyint(1) ,
  `p2_safeToysNotDiscussed` tinyint(1) ,
  `p2_sleepCryNotDiscussed` tinyint(1) ,
  `p2_soothabilityNotDiscussed` tinyint(1) ,
  `p2_homeVisitNotDiscussed` tinyint(1) ,
  `p2_bondingNotDiscussed` tinyint(1) ,
  `p2_pFatigueNotDiscussed` tinyint(1) ,
  `p2_famConflictNotDiscussed` tinyint(1) ,
  `p2_siblingsNotDiscussed` tinyint(1) ,
  `p2_childCareNotDiscussed` tinyint(1) ,
  `p2_2ndSmokeNotDiscussed` tinyint(1) ,
  `p2_teethingNotDiscussed` tinyint(1) ,
  `p2_altMedNotDiscussed` tinyint(1) ,
  `p2_pacifierNotDiscussed` tinyint(1) ,
  `p2_tmpControlNotDiscussed` tinyint(1) ,
  `p2_feverNotDiscussed` tinyint(1) ,
  `p2_sunExposureNotDiscussed` tinyint(1) ,
  `p2_pesticidesNotDiscussed` tinyint(1) ,
  `p2_readingNotDiscussed` tinyint(1) ,
  `p2_noCoughMedNotDiscussed` tinyint(1) ,
  `p2_eyesNotDiscussed` tinyint(1) ,
  `p2_coosNotDiscussed` tinyint(1) ,
  `p2_headUpTummyNotDiscussed` tinyint(1) ,
  `p2_cuddledNotDiscussed` tinyint(1) ,
  `p2_2sucksNotDiscussed` tinyint(1) ,
  `p2_smilesNotDiscussed` tinyint(1) ,
  `p2_noParentsConcerns2mNotDiscussed` tinyint(1) ,
  `p2_movingObjNotDiscussed` tinyint(1) ,
  `p2_respondsNotDiscussed` tinyint(1) ,
  `p2_headSteadyNotDiscussed` tinyint(1) ,
  `p2_holdsObjNotDiscussed` tinyint(1) ,
  `p2_laughsNotDiscussed` tinyint(1) ,
  `p2_noParentsConcerns4mNotDiscussed` tinyint(1) ,
  `p2_turnsHeadNotDiscussed` tinyint(1) ,
  `p2_makesSoundNotDiscussed` tinyint(1) ,
  `p2_vocalizesNotDiscussed` tinyint(1) ,
  `p2_rollsNotDiscussed` tinyint(1) ,
  `p2_sitsNotDiscussed` tinyint(1) ,
  `p2_reachesGraspsNotDiscussed` tinyint(1) ,
  `p2_noParentsConcerns6mNotDiscussed` tinyint(1) ,
  `p2_fontanelles2mNotDiscussed` tinyint(1) ,
  `p2_eyes2mNotDiscussed` tinyint(1) ,
  `p2_corneal2mNotDiscussed` tinyint(1) ,
  `p2_hearing2mNotDiscussed` tinyint(1) ,
  `p2_heart2mNotDiscussed` tinyint(1) ,
  `p2_hips2mNotDiscussed` tinyint(1) ,
  `p2_muscleTone2mNotDiscussed` tinyint(1) ,
  `p2_fontanelles4mNotDiscussed` tinyint(1) ,
  `p2_eyes4mNotDiscussed` tinyint(1) ,
  `p2_corneal4mNotDiscussed` tinyint(1) ,
  `p2_hearing4mNotDiscussed` tinyint(1) ,
  `p2_hips4mNotDiscussed` tinyint(1) ,
  `p2_muscleTone4mNotDiscussed` tinyint(1) ,
  `p2_fontanelles6mNotDiscussed` tinyint(1) ,
  `p2_eyes6mNotDiscussed` tinyint(1) ,
  `p2_corneal6mNotDiscussed` tinyint(1) ,
  `p2_hearing6mNotDiscussed` tinyint(1) ,
  `p2_hips6mNotDiscussed` tinyint(1) ,
  `p2_muscleTone6mNotDiscussed` tinyint(1) ,
  `p2_hepatitisVaccine6mNo` tinyint(1) ,
  `p2_tb6mOk` tinyint(1) ,
  `p2_tb6mNotDiscussed` tinyint(1) ,
  `p3_breastFeeding9mNo` tinyint(1) ,
  `p3_breastFeeding9mNotDiscussed` tinyint(1) ,
  `p3_formulaFeeding9mNo` tinyint(1) ,
  `p3_formulaFeeding9mNotDiscussed` tinyint(1) ,
  `p3_bottle9mNotDiscussed` tinyint(1) ,
  `p3_liquids9mNotDiscussed` tinyint(1) ,
  `p3_cereal9mNotDiscussed` tinyint(1) ,
  `p3_introCowMilk9mNotDiscussed` tinyint(1) ,
  `p3_egg9mNotDiscussed` tinyint(1) ,
  `p3_choking9mNotDiscussed` tinyint(1) ,
  `p3_breastFeeding12mNo` tinyint(1) ,
  `p3_breastFeeding12mNotDiscussed` tinyint(1) ,
  `p3_homoMilk12mNo` tinyint(1) ,
  `p3_homoMilk12mNotDiscussed` tinyint(1) ,
  `p3_cup12mNotDiscussed` tinyint(1) ,
  `p3_appetite12mNotDiscussed` tinyint(1) ,
  `p3_choking12mNotDiscussed` tinyint(1) ,
  `p3_breastFeeding15mNo` tinyint(1) ,
  `p3_breastFeeding15mNotDiscussed` tinyint(1) ,
  `p3_homoMilk15mNo` tinyint(1) ,
  `p3_homoMilk15mNotDiscussed` tinyint(1) ,
  `p3_choking15mNotDiscussed` tinyint(1) ,
  `p3_cup15mNotDiscussed` tinyint(1) ,
  `p3_poisonsNotDiscussed` tinyint(1) ,
  `p3_carSeatNotDiscussed` tinyint(1) ,
  `p3_firearmSafetyNotDiscussed` tinyint(1) ,
  `p3_smokeSafetyNotDiscussed` tinyint(1) ,
  `p3_hotWaterNotDiscussed` tinyint(1) ,
  `p3_electricNotDiscussed` tinyint(1) ,
  `p3_fallsNotDiscussed` tinyint(1) ,
  `p3_safeToysNotDiscussed` tinyint(1) ,
  `p3_sleepCryNotDiscussed` tinyint(1) ,
  `p3_soothabilityNotDiscussed` tinyint(1) ,
  `p3_homeVisitNotDiscussed` tinyint(1) ,
  `p3_parentingNotDiscussed` tinyint(1) ,
  `p3_pFatigueNotDiscussed` tinyint(1) ,
  `p3_famConflictNotDiscussed` tinyint(1) ,
  `p3_siblingsNotDiscussed` tinyint(1) ,
  `p3_childCareNotDiscussed` tinyint(1) ,
  `p3_2ndSmokeNotDiscussed` tinyint(1) ,
  `p3_teethingNotDiscussed` tinyint(1) ,
  `p3_altMedNotDiscussed` tinyint(1) ,
  `p3_pacifierNotDiscussed` tinyint(1) ,
  `p3_feverNotDiscussed` tinyint(1) ,
  `p3_activeNotDiscussed` tinyint(1) ,
  `p3_readingNotDiscussed` tinyint(1) ,
  `p3_footwearNotDiscussed` tinyint(1) ,
  `p3_coughMedNotDiscussed` tinyint(1) ,
  `p3_sunExposureNotDiscussed` tinyint(1) ,
  `p3_checkSerumNotDiscussed` tinyint(1) ,
  `p3_pesticidesNotDiscussed` tinyint(1) ,
  `p3_hiddenToyNotDiscussed` tinyint(1) ,
  `p3_soundsNotDiscussed` tinyint(1) ,
  `p3_responds2peopleNotDiscussed` tinyint(1) ,
  `p3_makeSoundsNotDiscussed` tinyint(1) ,
  `p3_sitsNotDiscussed` tinyint(1) ,
  `p3_standsNotDiscussed` tinyint(1) ,
  `p3_thumbNotDiscussed` tinyint(1) ,
  `p3_playGamesNotDiscussed` tinyint(1) ,
  `p3_attention9mNotDiscussed` tinyint(1) ,
  `p3_noParentsConcerns9mNotDiscussed` tinyint(1) ,
  `p3_respondsNotDiscussed` tinyint(1) ,
  `p3_simpleRequestsNotDiscussed` tinyint(1) ,
  `p3_consonantNotDiscussed` tinyint(1) ,
  `p3_says3wordsNotDiscussed` tinyint(1) ,
  `p3_shufflesNotDiscussed` tinyint(1) ,
  `p3_showDistressNotDiscussed` tinyint(1) ,
  `p3_pull2standNotDiscussed` tinyint(1) ,
  `p3_followGazeNotDiscussed` tinyint(1) ,
  `p3_noParentsConcerns12mNotDiscussed` tinyint(1) ,
  `p3_says5wordsNotDiscussed` tinyint(1) ,
  `p3_fingerFoodsNotDiscussed` tinyint(1) ,
  `p3_walksSidewaysNotDiscussed` tinyint(1) ,
  `p3_showsFearStrangersNotDiscussed` tinyint(1) ,
  `p3_crawlsStairsNotDiscussed` tinyint(1) ,
  `p3_squatsNotDiscussed` tinyint(1) ,
  `p3_noParentsConcerns15mNotDiscussed` tinyint(1) ,
  `p3_fontanelles9mNotDiscussed` tinyint(1) ,
  `p3_eyes9mNotDiscussed` tinyint(1) ,
  `p3_corneal9mNotDiscussed` tinyint(1) ,
  `p3_hearing9mNotDiscussed` tinyint(1) ,
  `p3_hips9mNotDiscussed` tinyint(1) ,
  `p3_fontanelles12mNotDiscussed` tinyint(1) ,
  `p3_eyes12mNotDiscussed` tinyint(1) ,
  `p3_corneal12mNotDiscussed` tinyint(1) ,
  `p3_hearing12mNotDiscussed` tinyint(1) ,
  `p3_tonsil12mNotDiscussed` tinyint(1) ,
  `p3_hips12mNotDiscussed` tinyint(1) ,
  `p3_fontanelles15mNotDiscussed` tinyint(1) ,
  `p3_eyes15mNotDiscussed` tinyint(1) ,
  `p3_corneal15mNotDiscussed` tinyint(1) ,
  `p3_hearing15mNotDiscussed` tinyint(1) ,
  `p3_tonsil15mNotDiscussed` tinyint(1) ,
  `p3_hips15mNotDiscussed` tinyint(1) ,
  `p3_antiHB9mNotDiscussed` tinyint(1) ,
  `p3_antiHB9mOk` tinyint(1) ,
  `p3_hemoglobin9mOk` tinyint(1) ,
  `p3_hemoglobin9mNotDiscussed` tinyint(1) ,
  `p3_hemoglobin12mOk` tinyint(1) ,
  `p3_hemoglobin12mNotDiscussed` tinyint(1) ,
  `p4_breastFeeding18mNo` tinyint(1) ,
  `p4_breastFeeding18mNotDiscussed` tinyint(1) ,
  `p4_homoMilk18mNo` tinyint(1) ,
  `p4_homoMilk18mNotDiscussed` tinyint(1) ,
  `p4_bottle18mNotDiscussed` tinyint(1) ,
  `p4_homo2percent24mNo` tinyint(1) ,
  `p4_homo2percent24mNotDiscussed` tinyint(1) ,
  `p4_lowerfatdiet24mNotDiscussed` tinyint(1) ,
  `p4_foodguide24mNotDiscussed` tinyint(1) ,
  `p4_2pMilk48mNo` tinyint(1) ,
  `p4_2pMilk48mNotDiscussed` tinyint(1) ,
  `p4_foodguide48mNotDiscussed` tinyint(1) ,
  `p4_carSeat18mNotDiscussed` tinyint(1) ,
  `p4_bathSafetyNotDiscussed` tinyint(1) ,
  `p4_safeToysNotDiscussed` tinyint(1) ,
  `p4_parentChild18mNotDiscussed` tinyint(1) ,
  `p4_discipline18mNotDiscussed` tinyint(1) ,
  `p4_pFatigue18mNotDiscussed` tinyint(1) ,
  `p4_highRisk18mNotDiscussed` tinyint(1) ,
  `p4_socializing18mNotDiscussed` tinyint(1) ,
  `p4_weanPacifier18mNotDiscussed` tinyint(1) ,
  `p4_dentalCareNotDiscussed` tinyint(1) ,
  `p4_toiletLearning18mNotDiscussed` tinyint(1) ,
  `p4_encourageReading18mNotDiscussed` tinyint(1) ,
  `p4_carSeat24mNotDiscussed` tinyint(1) ,
  `p4_bikeHelmetsNotDiscussed` tinyint(1) ,
  `p4_firearmSafetyNotDiscussed` tinyint(1) ,
  `p4_smokeSafetyNotDiscussed` tinyint(1) ,
  `p4_matchesNotDiscussed` tinyint(1) ,
  `p4_waterSafetyNotDiscussed` tinyint(1) ,
  `p4_parentChild24mNotDiscussed` tinyint(1) ,
  `p4_discipline24mNotDiscussed` tinyint(1) ,
  `p4_highRisk24mNotDiscussed` tinyint(1) ,
  `p4_pFatigue24mNotDiscussed` tinyint(1) ,
  `p4_famConflictNotDiscussed` tinyint(1) ,
  `p4_siblingsNotDiscussed` tinyint(1) ,
  `p4_2ndSmokeNotDiscussed` tinyint(1) ,
  `p4_dentalCleaningNotDiscussed` tinyint(1) ,
  `p4_noPacifier24mNotDiscussed` tinyint(1) ,
  `p4_altMedNotDiscussed` tinyint(1) ,
  `p4_toiletLearning24mNotDiscussed` tinyint(1) ,
  `p4_noCough24mNotDiscussed` tinyint(1) ,
  `p4_activeNotDiscussed` tinyint(1) ,
  `p4_socializing24mNotDiscussed` tinyint(1) ,
  `p4_readingNotDiscussed` tinyint(1) ,
  `p4_dayCareNotDiscussed` tinyint(1) ,
  `p4_sunExposureNotDiscussed` tinyint(1) ,
  `p4_pesticidesNotDiscussed` tinyint(1) ,
  `p4_checkSerumNotDiscussed` tinyint(1) ,
  `p4_manageableNotDiscussed` tinyint(1) ,
  `p4_otherChildrenNotDiscussed` tinyint(1) ,
  `p4_soothabilityNotDiscussed` tinyint(1) ,
  `p4_comfortNotDiscussed` tinyint(1) ,
  `p4_pointsNotDiscussed` tinyint(1) ,
  `p4_getAttnNotDiscussed` tinyint(1) ,
  `p4_recsNameNotDiscussed` tinyint(1) ,
  `p4_points2wantNotDiscussed` tinyint(1) ,
  `p4_looks4toyNotDiscussed` tinyint(1) ,
  `p4_initSpeechNotDiscussed` tinyint(1) ,
  `p4_says20wordsNotDiscussed` tinyint(1) ,
  `p4_4consonantsNotDiscussed` tinyint(1) ,
  `p4_walksbackNotDiscussed` tinyint(1) ,
  `p4_feedsSelfNotDiscussed` tinyint(1) ,
  `p4_removesHatNotDiscussed` tinyint(1) ,
  `p4_noParentsConcerns18mNotDiscussed` tinyint(1) ,
  `p4_2wSentenceNotDiscussed` tinyint(1) ,
  `p4_one2stepdirectionsNotDiscussed` tinyint(1) ,
  `p4_walksbackwardNotDiscussed` tinyint(1) ,
  `p4_runsNotDiscussed` tinyint(1) ,
  `p4_smallContainerNotDiscussed` tinyint(1) ,
  `p4_pretendsPlayNotDiscussed` tinyint(1) ,
  `p4_newSkillsNotDiscussed` tinyint(1) ,
  `p4_noParentsConcerns24mNotDiscussed` tinyint(1) ,
  `p4_3directionsNotDiscussed` tinyint(1) ,
  `p4_asksQuestionsNotDiscussed` tinyint(1) ,
  `p4_upDownStairsNotDiscussed` tinyint(1) ,
  `p4_undoesZippersNotDiscussed` tinyint(1) ,
  `p4_tries2comfortNotDiscussed` tinyint(1) ,
  `p4_noParentsConcerns48mNotDiscussed` tinyint(1) ,
  `p4_2directionsNotDiscussed` tinyint(1) ,
  `p4_5ormoreWordsNotDiscussed` tinyint(1) ,
  `p4_walksUpStairsNotDiscussed` tinyint(1) ,
  `p4_twistslidsNotDiscussed` tinyint(1) ,
  `p4_sharesSometimeNotDiscussed` tinyint(1) ,
  `p4_playMakeBelieveNotDiscussed` tinyint(1) ,
  `p4_turnsPagesNotDiscussed` tinyint(1) ,
  `p4_listenMusikNotDiscussed` tinyint(1) ,
  `p4_noParentsConcerns36mNotDiscussed` tinyint(1) ,
  `p4_countsOutloudNotDiscussed` tinyint(1) ,
  `p4_speaksClearlyNotDiscussed` tinyint(1) ,
  `p4_throwsCatchesNotDiscussed` tinyint(1) ,
  `p4_hops1footNotDiscussed` tinyint(1) ,
  `p4_dressesUndressesNotDiscussed` tinyint(1) ,
  `p4_obeysAdultNotDiscussed` tinyint(1) ,
  `p4_retellsStoryNotDiscussed` tinyint(1) ,
  `p4_separatesNotDiscussed` tinyint(1) ,
  `p4_noParentsConcerns60mNotDiscussed` tinyint(1) ,
  `p4_fontanellesClosedNotDiscussed` tinyint(1) ,
  `p4_eyes18mNotDiscussed` tinyint(1) ,
  `p4_corneal18mNotDiscussed` tinyint(1) ,
  `p4_hearing18mNotDiscussed` tinyint(1) ,
  `p4_tonsil18mNotDiscussed` tinyint(1) ,
  `p4_bloodpressure24mNotDiscussed` tinyint(1) ,
  `p4_eyes24mNotDiscussed` tinyint(1) ,
  `p4_corneal24mNotDiscussed` tinyint(1) ,
  `p4_hearing24mNotDiscussed` tinyint(1) ,
  `p4_tonsil24mNotDiscussed` tinyint(1) ,
  `p4_bloodpressure48mNotDiscussed` tinyint(1) ,
  `p4_eyes48mNotDiscussed` tinyint(1) ,
  `p4_corneal48mNotDiscussed` tinyint(1) ,
  `p4_hearing48mNotDiscussed` tinyint(1) ,
  `p4_tonsil48mNotDiscussed` tinyint(1) ,
  `p1_pNutrition1w` text,
  `p1_pNutrition2w` text,
  `p1_pNutrition1m` text,
  `p1_pEducation` text,
  `p1_pPhysical1w` text,
  `p1_pPhysical2w` text,
  `p1_pPhysical1m` text,
  `p1_immunization1w` text,
  `p1_immunization2w` text,
  `p1_immunization1m` text,
  `p2_nutrition6m` text,
  `p2_education` text,
  `p2_physical2m` text,
  `p2_physical4m` text,
  `p2_physical6m` text,
  `p2_immunization6m` text,
  `p3_nutrition9m` text,
  `p3_education` text,
  `p3_physical9m` text,
  `p3_physical12m` text,
  `p3_physical15m` text,
  `p4_nutrition18m` text,
  `p4_nutrition24m` text,
  `p4_nutrition48m` text,
  `p4_education18m` text,
  `p4_education48m` text,
  `p4_development18m` text,
  `p4_development24m` text,
  `p4_development48m` text,
  `p4_development36m` text,
  `p4_development60m` text,
  `p4_physical18m` text,
  `p4_physical24m` text,
  `p4_physical48m` text,
  `p4_nippisingattained` text,
  PRIMARY KEY (`ID`),
  KEY `formRourke2009_demographic_no` (`demographic_no`)
) ENGINE=MyISAM ;

CREATE TABLE `formLabReq10` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `formEdited` timestamp NOT NULL,
  `b_glucose` tinyint(1),
  `b_glucose_random` tinyint(1),
  `b_glucose_fasting` tinyint(1),
  `b_hba1c` tinyint(1),
  `b_creatinine` tinyint(1),
  `b_uricAcid` tinyint(1),
  `b_sodium` tinyint(1),
  `b_potassium` tinyint(1),
  `b_chloride` tinyint(1),
  `b_ck` tinyint(1),
  `b_alt` tinyint(1),
  `b_alkPhosphatase` tinyint(1),
  `ohip` tinyint(1),
  `formCreated` date,
  `patientFirstName` varchar(40),
  `b_timeNextDose2` varchar(20),
  `clinicCity` varchar(40),
  `b_timeNextDose1` varchar(20),
  `b_timeLastDose2` varchar(20),
  `b_timeLastDose1` varchar(20),
  `provider_no` int(11),
  `m_vaginalRectal` tinyint(1),
  `m_vaginal` tinyint(1),
  `b_acRatioUrine` tinyint(1),
  `healthNumber` varchar(20),
  `patientCity` varchar(40),
  `b_patientsTelNo` varchar(40),
  `clinicianContactUrgent` varchar(40),
  `b_childsAgeDays` varchar(20),
  `b_tsh` tinyint(1),
  `b_timeCollected2` varchar(20),
  `b_timeCollected1` varchar(20),
  `b_therapeuticDrugMonitoring` tinyint(1),
  `i_rubella` tinyint(1),
  `m_cervical` tinyint(1),
  `patientAddress` varchar(60),
  `b_vitaminB12` tinyint(1),
  `m_blank` tinyint(1),
  `reqProvName` varchar(60),
  `v_chronicHepatitis` tinyint(1),
  `version` varchar(6),
  `oprn` varchar(40),
  `b_albumin` tinyint(1),
  `aci` text,
  `patientPC` varchar(10),
  `b_urinalysis` tinyint(1),
  `h_cbc` tinyint(1),
  `form_class` tinyint(1),
  `sex` varchar(8),
  `i_pregnancyTest` tinyint(1),
  `submit` tinyint(1),
  `v_acuteHepatitis` tinyint(1),
  `birthDate` date,
  `patientBirthMth` varchar(25),
  `phoneNumber` varchar(20),
  `m_otherSwabsSource` varchar(60),
  `m_otherSwabsPus` tinyint(1),
  `clinicAddress` varchar(100),
  `m_gcSource` varchar(60),
  `b_childsAgeHours` varchar(20),
  `m_throat` tinyint(1),
  `patientLastName` varchar(40),
  `m_sputum` tinyint(1),
  `b_neonatalBilirubin` tinyint(1),
  `m_fecalOccultBlood` tinyint(1),
  `m_urine` tinyint(1),
  `m_blankText` varchar(100),
  `b_nameDrug2` varchar(100),
  `m_stoolOvaParasites` tinyint(1),
  `b_nameDrug1` varchar(100),
  `m_gc` tinyint(1),
  `i_prenatal` tinyint(1),
  `h_prothrombinTime` tinyint(1),
  `patientBirthYear` varchar(10),
  `m_chlamydiaSource` varchar(60),
  `i_repeatPrenatalAntibodies` tinyint(1),
  `b_ferritin` tinyint(1),
  `wcb` tinyint(1),
  `v_immuneStatus` tinyint(1),
  `m_stoolCulture` tinyint(1),
  `province` varchar(20),
  `m_woundSource` varchar(60),
  `patientBirthDay` varchar(30),
  `demographic_no` int(11),
  `i_mononucleosisScreen` tinyint(1),
  `b_lipidAssessment` tinyint(1),
  `m_wound` tinyint(1),
  `provName` varchar(60),
  `thirdParty` tinyint(1),
  `clinicName` varchar(60),
  `b_bilirubin` tinyint(1),
  `m_specimenCollectionTime` varchar(15),
  `o_otherTests16` varchar(150),
  `o_otherTests15` varchar(150),
  `o_otherTests14` varchar(150),
  `o_otherTests13` varchar(150),
  `o_otherTests12` varchar(150),
  `o_otherTests11` varchar(150),
  `o_otherTests10` varchar(150),
  `o_otherTests9` varchar(150),
  `o_otherTests8` varchar(150),
  `o_otherTests7` varchar(150),
  `o_otherTests6` varchar(150),
  `o_specimenCollectionDate` date,
  `o_otherTests5` varchar(150),
  `clinicPC` varchar(10),
  `o_otherTests4` varchar(150),
  `o_otherTests3` varchar(150),
  `o_otherTests2` varchar(150),
  `b_cliniciansTelNo` varchar(40),
  `o_otherTests1` varchar(150),
  `patientName` varchar(40),
  `b_dateSigned` date,
  `practitionerNo` varchar(20),
  `m_chlamydia` tinyint(1),
  `v_immune_HepatitisC` tinyint(1),
  `v_immune_HepatitisB` tinyint(1),
  `v_immune_HepatitisA` tinyint(1),
  `fobt_nonCCC` tinyint(1),
  `fobt_CCC` tinyint(1),
  `psa_total` tinyint(1),
  `psa_free` tinyint(1),
  `psa_insured` tinyint(1),
  `psa_uninsured` tinyint(1),
  `copy2clinician` tinyint(1),
  `copyLname` varchar(32),
  `copyFname` varchar(32),
  `copyAddress` varchar(100),
  `vitd_uninsured` tinyint(1),
  `vitd_insured` tinyint(1),
  `hcType` varchar(4),
  `male` tinyint(1),
  `female` tinyint(1),
  `patientChartNo` varchar(20),
  `letterhead` varchar(25),
  PRIMARY KEY (`ID`)
);

CREATE TABLE `batch_billing` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `demographic_no` int(10),
  `billing_provider_no` varchar(6),
  `service_code` varchar(10),
  `dxcode` varchar(5),
  `billing_amount` varchar(10),
  `lastbilled_date` date,
  `create_date` timestamp,
  `creator` varchar(6),
  PRIMARY KEY (`id`)
);

create table billing_on_premium (
    premium_id int (10) NOT NULL auto_increment primary key, 
    raheader_no int(6) NOT NULL, provider_no varchar(6), 
    providerohip_no varchar(6) NOT NULL, 
    pay_date date NOT NULL, 
    amount_pay varchar(10) NOT NULL, 
    status tinyint(1) NOT NULL, 
    create_date timestamp NOT NULL, 
    creator varchar(6) NOT NULL
);


CREATE TABLE `formPositionHazard` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `demographic_no` int(11),
  `formCreated` date,
  `formEdited`  timestamp NOT NULL,
  `supervisor` varchar(100),
  `formCreatedBy` varchar(6),
  `Acrylonitrile` varchar(1),
  `JobReclassify` tinyint(1),
  `NewHire` tinyint(1),
  `ProcedureChange` tinyint(1),
  `staffName` varchar(500),
  `staffPosition` varchar(500),
  `staffPhone` varchar(500),
  `staffJobSite` varchar(500),
  `staffDept` varchar(500),
  `staffEmail` varchar(500),
  `supervisorName` varchar(500),
  `supervisorEmail` varchar(500),
  `supervisorCampusAddress` varchar(500),
  `supervisorPhone` varchar(500),
  `staffFaculty` varchar(500),
  `Asbestos` varchar(1),
  `EthyleneOxide` varchar(1),
  `Lead` varchar(1),
  `Silica` varchar(1),
  `Arsenic` varchar(1),
  `Benzene` varchar(1),
  `Isocyanates` varchar(1),
  `Mercury` varchar(1),
  `VinylChloride` varchar(1),
  `CompressedGases` varchar(1),
  `MaterialsSeriousEffects` varchar(1),
  `ReactiveMaterials` varchar(1),
  `FlammableCombustible` varchar(1),
  `CorrosiveMaterials` varchar(1),
  `MaterialsOtherToxicEffects` varchar(1),
  `OxidizingMaterials` varchar(1),
  `AgricultureChemicals` varchar(1),
  `ChemicalNames` varchar(500),
  `ChemicalHowItsUsed` varchar(500),
  `ContainmentLevel1` varchar(1),
  `ContainmentLevel2` varchar(1),
  `ContainmentLevel3` varchar(1),
  `AnimalCareFacility` varchar(1),
  `SheepContainmentUnit` varchar(1),
  `NonHumanPrimate` varchar(1),
  `ContainmentLevel3Area` varchar(1),
  `PrimaryCulture` varchar(1),
  `Cadavers` varchar(1),
  `BloodProducts` varchar(1),
  `PrimaryPatientCare` varchar(1),
  `OtherHumanBiohazard` text,
  `Primates` varchar(1),
  `DogsCats` varchar(1),
  `Sheep` varchar(1),
  `WildMammals` varchar(1),
  `Rodents` varchar(1),
  `OtherAnimalBiohazard` varchar(500),
  `OtherBiohazard` varchar(500),
  `PathogenicParasites` varchar(500),
  `UltravioletEmitter` varchar(1),
  `InfraredEmitter` varchar(1),
  `Irradiators` varchar(1),
  `Vibration` varchar(1),
  `ExtremeHeat` varchar(1),
  `RadioactiveSubstance` varchar(1),
  `MicrowaveEmittingDevice` varchar(1),
  `XrayEmittingDevice` varchar(1),
  `RadioFrequency` varchar(1),
  `ExtremeCold` varchar(1),
  `Ultrasound` varchar(1),
  `Infrasound` varchar(1),
  `Gamma` varchar(1),
  `HighNoiseLevels` varchar(1),
  `Laser3B` varchar(1),
  `Laser4` varchar(1),
  `MagneticField` varchar(1),
  `Nanotechnology` text,
  `Driving` varchar(1),
  `HighVoltage` varchar(1),
  `ConfinedSpaceEntry` varchar(1),
  `Heights` varchar(1),
  `ComputerWork` varchar(1),
  `RepetitiveWork` varchar(1),
  `AwkwardPositions` varchar(1),
  `WasteManagement` tinyint(1),
  `RadiationSafety` tinyint(1),
  `EmployeeSafety` tinyint(1),
  `XrayTraining` tinyint(1),
  `AnimalHandling` tinyint(1),
  `BiosafetyTraining` tinyint(1),
  `FormCompletedBy` varchar(500),
  `AdditionalNotes` text,
  `WHIMS` tinyint(1),
  `OtherCode` varchar(500),
  `ProcedureName` text,
  `SubstanceForm` text,
  PRIMARY KEY (`ID`));

create table frm_labreq_preset (
	preset_id int (10) NOT NULL auto_increment primary key,
	lab_type varchar(255)  NOT NULL,
	prop_name varchar(255) NOT NULL,
	prop_value varchar(255) NOT NULL,
	status int (1) NOT NULL
);
